# Generated by Django 5.0.3 on 2024-03-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('price_per_minute', models.FloatField()),
                ('image_url', models.CharField(max_length=120)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('drop_time', models.DateTimeField()),
                ('booking_fare', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApi.cab')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='BookingApi.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='BookingApi.city')),
            ],
            options={
                'ordering': ['-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('city_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_a', to='BookingApi.city')),
                ('city_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_b', to='BookingApi.city')),
            ],
            options={
                'unique_together': {('city_a', 'city_b')},
            },
        ),
    ]
